#! /bin/sh

### lesgooo ###

# (re-)start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config border_width         2
#bspc config window_gap          12
bspc config border_width	4
bspc config window_gap		8

# colors - TODO: make nice (catppuccin)
bspc config normal_border_color		"#45475A"
#bspc config normal_border_color		"#601080"
bspc config active_border_color		"#94E2D5"
bspc config focused_border_color	"#F5C2E7"
bspc config presel_border_color		"#A6E3A1"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# polybar lesgoo
# could do launch script with logs or just roll
# make sure ipc is true in all bars
polybar-msg cmd quit
# dont use the nuclear option (killall)
# start the bar(s)
#polybar name_of_bar &
polybar first &

# call the ~/.fehbg script for wallpaper
#$HOME/.fehbg &
$HOME/.scripts/feh_setbg.sh

